---
- name: Install Google Chrome
  hosts: all
  become: true

  tasks:
    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Google Chrome GPG key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present
